pipeline {
    agent any

    environment {
        IMAGE_NAME = "deepfake-detector"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/naik-shashank/deepfake-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Model_Api') {
                    sh 'eval $(minikube docker-env) && docker build -t deepfake-detector .'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('Model_Api') {
                    sh 'kubectl apply -f k8s-deployment.yaml'
                }
            }
        }
    }
}
