apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfake-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepfake
  template:
    metadata:
      labels:
        app: deepfake
    spec:
      containers:
        - name: deepfake-container
          image: deepfake-detector
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: deepfake-service
spec:
  type: ClusterIP
  selector:
    app: deepfake
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007 # You can access app at localhost:30007
